version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile

    image: "myapi"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    image: "frontend"
    ports:
      - "3000:3000"


  