version: "3.7"

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile

    image: "exclusible_backend"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    image: "exclusible_frontend"
    ports:
      - "3000:3000"


  